- name: "set up systemd file"
  template: 
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/node.service"
  when: "nodejs_systemd_start is defined"
  
- name: "enable and start systemd service"
  systemd:
    name: "node"
    enabled: true
    daemon_reload: true
  notify: "start node"

  
